// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaAHbYi0m84Sj_VTkKJyQbnRPDjvTWQHk',
    appId: '1:189709970345:web:36f04ca3faa99e182df2b8',
    messagingSenderId: '189709970345',
    projectId: 'taskmanagment-ab14e',
    authDomain: 'taskmanagment-ab14e.firebaseapp.com',
    storageBucket: 'taskmanagment-ab14e.firebasestorage.app',
    measurementId: 'G-9YT15XFVRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1LX-PUnaDnpTFNTwXTXIDf579DbNZg8',
    appId: '1:189709970345:android:34ee9929531166d92df2b8',
    messagingSenderId: '189709970345',
    projectId: 'taskmanagment-ab14e',
    storageBucket: 'taskmanagment-ab14e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbV0xSLkQSZXFXj750Z_kRSIPc3vtULvg',
    appId: '1:189709970345:ios:91ef56372739b64f2df2b8',
    messagingSenderId: '189709970345',
    projectId: 'taskmanagment-ab14e',
    storageBucket: 'taskmanagment-ab14e.firebasestorage.app',
    iosBundleId: 'com.tickTackGo.pr1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbV0xSLkQSZXFXj750Z_kRSIPc3vtULvg',
    appId: '1:189709970345:ios:91ef56372739b64f2df2b8',
    messagingSenderId: '189709970345',
    projectId: 'taskmanagment-ab14e',
    storageBucket: 'taskmanagment-ab14e.firebasestorage.app',
    iosBundleId: 'com.tickTackGo.pr1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaAHbYi0m84Sj_VTkKJyQbnRPDjvTWQHk',
    appId: '1:189709970345:web:a43a3d7a0e357a7e2df2b8',
    messagingSenderId: '189709970345',
    projectId: 'taskmanagment-ab14e',
    authDomain: 'taskmanagment-ab14e.firebaseapp.com',
    storageBucket: 'taskmanagment-ab14e.firebasestorage.app',
    measurementId: 'G-GFJ3S48X1T',
  );
}
