###
POST http://127.0.0.1:8000/api/users/register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Ali3",
    "email": "alialmusfi3@gmail.com",
    "password": "aloosh1234",
    "how_to_use_website": "small_team",
    "what_do_you_do": "software_or_it",
    "how_did_you_get_here": "friends"
}

###
POST http://127.0.0.1:8000/api/users/send_otp/ HTTP/1.1
Content-Type: application/json

{
    "username": "Ali",
    "email": "alialmusfi@gmail.com",
    "password": "aloosh1234",
    "how_to_use_website": "small_team",
    "what_do_you_do": "software_or_it",
    "how_did_you_get_here": "friends"
}


###

POST http://127.0.0.1:8000/api/users/verify_register/ HTTP/1.1
Content-Type: application/json

{
    "username": "Ali",
    "email": "alialmusfi@gmail.com",
    "password": "aloosh1234",
    "how_to_use_website": "small_team",
    "what_do_you_do": "software_or_it",
    "how_did_you_get_here": "friends",
    "otp": "138182"
}

###
POST http://127.0.0.1:8000/api/users/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "alialmusfi3@gmail.com",
    "password": "aloosh1234"
}


###

POST http://127.0.0.1:8000/api/users/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0ODAwNjc5MCwiaWF0IjoxNzQ3OTIwMzkwLCJqdGkiOiIzNzU4ODIzZWYyMTE0YzZkYmY2MjA5YWM1ZWZkYTEzYyIsInVzZXJfaWQiOjZ9.zQJ-FsRXGGeywDzpifc2ngona2rLjatRwWFWyB0uPVY"
}

###
POST http://127.0.0.1:8000/api/workspaces/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMjE4Njg2LCJpYXQiOjE3NTEyMTUwODYsImp0aSI6ImE4YjY0NWIyNTdhYjQwOTNiMmQ1MGIxM2E1YmE5N2YwIiwidXNlcl9pZCI6MX0.aHlsd17w1BW3x9e81Cd9wrlcSoTrt8JeCMFzyi53wl4

{
    "title": "Workspace 1"
}
###

POST http://127.0.0.1:8000/api/projects/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxMjE4Njg2LCJpYXQiOjE3NTEyMTUwODYsImp0aSI6ImE4YjY0NWIyNTdhYjQwOTNiMmQ1MGIxM2E1YmE5N2YwIiwidXNlcl9pZCI6MX0.aHlsd17w1BW3x9e81Cd9wrlcSoTrt8JeCMFzyi53wl4

{
  "title": "SupProject 7",
  "color": "#ff0000",
  "workspace": 1,
  "parent_project": 1
}

###

GET http://127.0.0.1:8000/api/users?username__icontains=sha/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NDc4OTgwLCJpYXQiOjE3NDk0NzUzODAsImp0aSI6IjdmMWU1NTU0NzEzODQ2OTZiNTgxNzg3ZWVkNTY4MmJjIiwidXNlcl9pZCI6MX0.EFNStRmxCPibewFiuzlh6dnJtWphDsoKYrGf9JmUVeY

###

GET http://127.0.0.1:8000/api/users/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MzA1MTA3LCJpYXQiOjE3NDkzMDE1MDcsImp0aSI6ImRmNGM5MzAwNjRlZjQ3ZWU4M2I4MDAyOGRiY2QwNTIyIiwidXNlcl9pZCI6MX0.rPkb4dPLbwX5cYDyC4tUr8ZGp_rgYwkTCQhl3NksTHs


###
#invite user#
POST http://127.0.0.1:8000/api/workspaces/2/invite_user/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjU0OTM4LCJpYXQiOjE3NTUyNTEzMzgsImp0aSI6IjA3MTYxOTllMDlkMDQ3YmRhYjdmYmEyNDZjZmQ3OGQ1IiwidXNlcl9pZCI6Mn0.WyrGIcQTPY_3WdEt4mmHmRDaWgs5quSyL8tf0-fkMCA

{
    "receiver": 1

}

###

GET http://127.0.0.1:8000/api/users/show_invites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NDg0OTk5LCJpYXQiOjE3NTQ0ODEzOTksImp0aSI6IjQ5MzhiN2JmZjc2YzQ2YjZhNWMyMDI5MDlkY2FlNTQxIiwidXNlcl9pZCI6M30.xFHdvAvZewL9w8ToG4mTekVoNTY6mgAkEqil241LHfs


###


POST http://127.0.0.1:8000/api/users/show_sent_invites/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTI5OTE2LCJpYXQiOjE3NTU1MjYzMTYsImp0aSI6ImFhOTI1ZmY4YmM4MjRmODJhNzgyMGRkM2ZmM2RlZTUwIiwidXNlcl9pZCI6MX0.N70EnYfjlio945yIHlncczzWHm77UXcTAzlWBmtVfho

{
    "workspace": 1
}


###

POST http://127.0.0.1:8000/api/users/accept_invite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjU2MjY0LCJpYXQiOjE3NTUyNTI2NjQsImp0aSI6IjBkMWIzZTQ5MzUwYTQyMzU4YmI0YzJkYmE1NzQ3NDJiIiwidXNlcl9pZCI6MX0.l23U-kcwnFnEz613U4nSRa2Hdrx3y6ggjaFEUtuMrUg

{
    "invite": 4

}

###

POST http://127.0.0.1:8000/api/users/reject_invite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTY5NDY2LCJpYXQiOjE3NDg5NjU4NjYsImp0aSI6IjhhYjUxNjU1YTFhZDRlNjc4NGU4YjkzMjk3NGQ0OWVjIiwidXNlcl9pZCI6Mn0.xyPRnQ2TSwOi1fADLxPppjglNIYzP1gx1BEx6-m7iCk

{
    "invite_id": 5

}

###


POST http://127.0.0.1:8000/api/workspaces/2/cancel_invite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MjU0OTM4LCJpYXQiOjE3NTUyNTEzMzgsImp0aSI6IjA3MTYxOTllMDlkMDQ3YmRhYjdmYmEyNDZjZmQ3OGQ1IiwidXNlcl9pZCI6Mn0.WyrGIcQTPY_3WdEt4mmHmRDaWgs5quSyL8tf0-fkMCA

{
    "invite":4
}

###

GET http://127.0.0.1:8000/api/users/start_app/ HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Mjk3MTk5LCJpYXQiOjE3NDkyOTM1OTksImp0aSI6IjRmYTgwMzgyNTFiOTRhNDRiYzMwYWU3NTU1ZTQ4MjhhIiwidXNlcl9pZCI6Mn0.2FrXWHiOZRlfuWS9dBBiw__3MsQTA-TTvXrQCvxN5-E


