# Generated by Django 5.1.7 on 2025-08-27 15:28

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('expires_at', models.DateTimeField(default=users.models.otp_expires_date_time, editable=False)),
            ],
            options={
                'db_table': 'user_otp',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(default='defaults/users/default.png', upload_to=users.models.user_image_upload_path)),
                ('how_to_use_website', models.CharField(choices=[('own_tasks_management', 'Own Tasks Management'), ('small_team', 'Small Team'), ('medium_team', 'Medium Team')], max_length=20)),
                ('what_do_you_do', models.CharField(choices=[('software_or_it', 'Software Or It'), ('hr_or_operations', 'Hr Or Operations'), ('sales_and_marketing', 'Sales And Marketing'), ('education', 'Education'), ('finance', 'Finance'), ('health', 'Health'), ('student', 'Student'), ('architecture_engineer', 'Architecture Engineer'), ('other', 'Other')], max_length=21)),
                ('how_did_you_get_here', models.CharField(choices=[('google_search', 'Google Search'), ('friends', 'Friends'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=13)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_id', models.TextField(verbose_name='FCM Registration Token')),
                ('active', models.BooleanField(default=True, help_text='is this device currently active?')),
                ('device_type', models.CharField(blank=True, help_text='e.g., Android, iOS, Web', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
