# Generated by Django 5.1.7 on 2025-09-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace_Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(editable=False, max_length=255, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('valid', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_invitations',
            },
        ),
    ]
